General:
  run_name: "CI_test_run"


Signal:
  DataType: Phase2
Reconstruction:
  MaxHits: 12
  MinHits: 6
TDCFitting:
  max_iterations: 100
  tdc_max: 1000 #ns
  tdc_min: 0 #ns
  tdc_bins: 200
  adc_max: 300 #ns
  adc_min: 0 #ns
  adc_bins: 50
Simulator:
  tdc_time_delay: 70 #ns
  tdc_time_sigma: 10 #ns
  pulse_width_mean: 200 #ns
  pulse_width_sigma: 25 #ns
  nevents: 10  # Number of events to simulate

Geometry:
  multilayer_spacing: 6.536 #mm
  multilayers:
    multilayer1:
      tdcType: "446"
      radius: 15 #mm
      length: 100 #mm
      tube_spacing: .035 #mm
      activeTDCs: [True, True, True, True, True, True]
      TDC_ids: [1, 3, 5, 7, 9, 11]
      CSM_ids: [0, 0, 0, 0, 0, 0]
      material:
        type: "Aluminum"
        thickness: 0.4 #mm
    multilayer2:
      tdcType: "436"
      radius: 15 #mm
      length: 100 #mm
      tube_spacing: .035 #mm
      activeTDCs: [True, True, True, True, True, True]
      TDC_ids: [0, 2, 4, 6, 8, 10]
      CSM_ids: [0, 0, 0, 0, 0, 0]
      material:
        type: "Aluminum"
        thickness: 0.4 #mm